### ISSUE TITLE
SampleSheet.write()?

### ISSUE THREAD

**Issue by astewart-twist** [clintval/sample-sheet#12]
Hi there.  Cool lib!

Do you have any intention on adding the ability to use this to create new (and write) sample sheets?  Seems like most of the mechanics are already in place, probably just need a function to write back to string.

**Comment by clintval** [comment]
Yes I do! I made an early design decision to use Python code-style attributes (`snake_case` ) instead of the keys as parsed from the Sample Sheet (_e.g._ `I7_Index_ID`). My goal is to keep the syntax predictable but allow round trip reading, editing, and writing.

**Comment by astewart-twist** [comment]
Awesome!  

That's a good question - I can see the utility for someone wanting to maybe repair a problematic sample sheet or to re-use a previous sample sheet as a template with some slight modifications, etc.  My basic use case is simply programmatic _de novo_ generation of sample sheets in order to get around having to use Illumina's Experiment Manager.

**Comment by clintval** [comment]
Quick question before I work on this feature.

Do you know if order of the key-values in the `[Header]`, `[Settings]`, and samples in the `[Data]` section is important to preserve? Would a deterministic order be expected behavior in your `SampleSheet.write()` scenario?

-C

**Comment by astewart-twist** [comment]
Another good question.  I can't imagine it would - but it's a very strange format to begin with, so who knows.  It would be fairly easy to test by running `bcl2fastq` with a couple different sample sheets where the order of the key-value pairs are reordered.  I think I have some small runs I've used for testing demux options that I could try that out on.

On a similar note, I imagine there could be some formatting differences based on instrument platform, version of Illumina Experiment Manager or BaseSpace, etc.  For example, I see the following header in sample sheets generated from IEM:

```
[Header]
IEMFileVersion,4
```
imho, the safest bet is probably to be as generic as possible and place the burden of any formatting nuances on the user.  Otherwise I would imagine it could get quite complicated trying to incorporate some notion of 'format version' in the parsing and rendering logic.

Hope that's helpful!

**Comment by clintval** [comment]
Thanks @astewart-twist, I think I have a plan to get this done while maintaining the same API.

I like the idea of generating a sample sheet *de novo*. My thought is to add the key-value pairs for the sections in the order they are defined:

```python
>>> sample_sheet = SampleSheet()

>>> sample_sheet.header.IEMFileVersion = 4
>>> sample_sheet.header.Investigator_Name = 'john'

>>> sample_sheet.write(sys.stdout)

[Header]
IEMFileVersion, 4, ...
Investigator_Name, john, ...
...
```

I mostly use this library to retrsopectively look at sample key-values in post-analysis and have never used IEM so I appreciate your perspective.

**Comment by PertuyF** [comment]
Hi guys,
Nice effort!
I would also be interested into a *de novo* samplesheet generation.

Regarding your question about the order of key:value data in each sections, I guess it is not important. At least it is not mentioned in [Illumina's SampleSheet format spec](https://www.illumina.com/content/dam/illumina-marketing/documents/products/technotes/sequencing-sheet-format-specifications-technical-note-970-2017-004.pdf). But the order of the sections is (Header first, Data last, anything in between).
The order of the samples in the `[Data]` section is probably not important either.

**Comment by clintval** [comment]
Thanks! I plan on working on this feature this weekend.

**Comment by clintval** [comment]
Hi @astewart-twist, I implemented this feature and merged to `master`. You could also edit a sample sheet and write it back out.

https://github.com/clintval/sample-sheet#sample-sheet-creation

**Comment by astewart-twist** [comment]
Awesome @clintval , I'll check it out ASAP.

**Comment by astewart-twist** [comment]
@clintval is this version pip installed or do I need to install from github?

**Comment by clintval** [comment]
You will need to install from GitHub until I make a release:

```bash
$  pip install git+git://github.com/clintval/sample-sheet.git
```

should do it.

**Comment by astewart-twist** [comment]
Yeah I figured it out.  I've been having trouble with system vs homebrew managed pip/pip2/pip3 which threw me off.

The `.write()` method works great!  I'll try it out with a few upcoming runs and report back if there are any issues.

**Comment by clintval** [comment]
Hi @astewart-twist, happy to release [v0.3.0](https://github.com/clintval/sample-sheet/releases/tag/v0.3.0) this evening with this feature implemented.

I hope to continue writing sample sheets as detemrinistic so we can hash and diff sample sheets easily after modifying.

Thanks!
-C
