### ISSUE TITLE
Supporting TrueSight 170 sample sheets

### ISSUE THREAD

**Issue by slagelwa** [clintval/sample-sheet#37]
Would be wonderful if it supported the TrueSight 170 style sample sheets.

**Comment by clintval** [comment]
Could you provide an example or a link to documentation on the file format?

**Comment by slagelwa** [comment]
Absolutely.  It's pretty straightforward.  There's an additional "Manifest" section in the sample sheet that contains name/filename pairs (typically PoolRNA,MixRNA_Manifest.txt and PoolDNA,MixDNA_Manifest.txt) which are then used in the samples section via an additional Manifest column whose value must match what's in the manifest section  PoolRNA or PoolDNA).

Here's the illumina product page:

https://www.illumina.com/products/by-type/clinical-research-products/trusight-tumor-170.html

And an example  file:

https://support.illumina.com/content/dam/illumina-support/documents/downloads/software/trusight/trusight-tumor-170/trusight-tumor-170-v1-0-local-app-sample-sheet-template-1000000038524-00.zip

And the manual contains a good description of the sample sheet:

https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/trusight/trusight-tumor-170/trusight-tumor-170-v1-0-local-app-user-guide-1000000036413-00.pdf

**Comment by clintval** [comment]
Thanks! I'll add this in for another release. I've been meaning to support the `[Manifest]` section including arbitrary user-defined sections which is allowable by the general Illumina Sample Sheet specification.

**Comment by slagelwa** [comment]
Great!  Happy to help test.

**Comment by clintval** [comment]
Ok all set here! This library is still young so feel free to write back if you need more out of it!
