### ISSUE TITLE
Output as json

### ISSUE THREAD

**Issue by slagelwa** [clintval/sample-sheet#41]
Would be useful to have the option to output the sample sheet as json.

**Comment by clintval** [comment]
Closed with #44. @slagelwa thanks for the feature request!

You can now do:

```python
SampleSheet(filename).to_json()
```

And on the CLI:

```bash
$ sample-sheet to_json filename | jq
```

**Comment by clintval** [comment]
Hi @slagelwa I just made a new release on PyPi containing this feature.

```bash
$ pip install sample_sheet
```

Will get you the newest build.

https://github.com/clintval/sample-sheet/releases/tag/v0.6.0

**Comment by slagelwa** [comment]
Excellent.  Thanks!

**Comment by slagelwa** [comment]
Excellent.  Thanks!
