### ISSUE TITLE
Error installing with pip

### ISSUE THREAD

**Issue by nuin** [clintval/sample-sheet#45]
Getting a syntax error when installing on a fresh virtualenv system

```
(pipeline_run3) data_management> python
Python 3.4.5 (default, Sep 08 2016, 13:41:53) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
(pipeline_run3) pipeline@SequenceKing:~/cancerplus/code/data_management> pip3 install sample_sheet
Collecting sample_sheet
  Using cached https://files.pythonhosted.org/packages/fc/75/69cab3b91ea745a909bedc53f30789414eedc11ce2ebe6189733560a9583/sample_sheet-0.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5eqifgel/sample-sheet/setup.py", line 12
        URL = f'https://github.com/clintval/{PACKAGE_NAME}'
                                                          ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5eqifgel/sample-sheet/
```

**Comment by clintval** [comment]
Hi @nuin, only Python3.6+ is supported at the moment.

**Comment by nuin** [comment]
Ah, OK. We have this system with 3.4 installed where we do our bcl2fastq conversions and we are automating our sample sheet parsing. Is it hard to add compatibility to 3.4? I will check installing 3.6 on it.

Thanks.

**Comment by clintval** [comment]
It would not be hard to add Python 3.4+ compatibility. To do so I think I need to change/check two things:

- Drop the f-strings
- Check unit tests such that they do not rely on deterministic dictionary key order

If you can't port to Python 3.6 and still want Python 3.4 support, could you open a new issue with the request and I can review there?

FYI my initial intention was to keep this Python 3.6+ but I do understand many others are still locked into earlier Python 3 versions.

**Comment by nuin** [comment]
I will check tomorrow, if it's a no go on 3.6, I will let you know.

Thanks

**Comment by nuin** [comment]
I was able to install 3.6 on my machine, I am checking my code now.

Thanks
