### ISSUE TITLE
Error when attempting to parse non-comma-padded sample sheet files

### ISSUE THREAD

**Issue by andybearman** [clintval/sample-sheet#46]
Hi there, I'm having some trouble parsing sample sheet files that don't use the comma-padded format. E.g.
```ini
[Header]
IEM1FileVersion,4
Investigator Name,jdoe
Experiment Name,exp001
Date,11/16/2017
Workflow,SureSelectXT
Application,NextSeq FASTQ Only
Assay,SureSelectXT
Description,A description of this flow cell
Chemistry,Default

[Reads]
151
151

[Settings]
CreateFastqForIndexReads,1
BarcodeMismatches,2

[Data]
Sample_ID,Sample_Name,index,Description,Library_ID,Read_Structure,Reference_Name,Sample_Project,Target_Set
1823A,1823A-tissue,GAATCTGA,0.5x treatment,2017-01-20,151T8B151T,mm10,exp001,Intervals-001
1823B,1823B-tissue,AGCAGGAA,0.5x treatment,2017-01-20,151T8B151T,mm10,exp001,Intervals-001
1824A,1824A-tissue,GAGCTGAA,1.0x treatment,2017-01-20,151T8B151T,mm10,exp001,Intervals-001
1825A,1825A-tissue,AAACATCG,10.0x treatment,2017-01-20,151T8B151T,mm10,exp001,Intervals-001
1826A,1826A-tissue,GAGTTAGC,100.0x treatment,2017-01-20,151T8B151T,mm10,exp001,Intervals-001
1826B,1823A-tissue,CGAACTTA,0.5x treatment,2017-01-17,151T8B151T,mm10,exp001,Intervals-001
1829A,1823B-tissue,GATAGACA,0.5x treatment,2017-01-17,151T8B151T,mm10,exp001,Intervals-001
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sample_sheet/_sample_sheet.py", line 376, in __init__
    self._parse(str(self.path))
  File "sample_sheet/_sample_sheet.py", line 468, in _parse
    header_match = self._section_header_re.match(line[0])
IndexError: list index out of range
list index out of range
```
It seems the lack of commas is causing `csv.reader` to produce an empty array for the empty lines. Moving the [empty line check](https://github.com/clintval/sample-sheet/blob/master/sample_sheet/_sample_sheet.py#L470) to the top of the `for` block fixes this.

**Comment by clintval** [comment]
This format should be supported as it is described on page 4 of [this manual](https://www.illumina.com/content/dam/illumina-marketing/documents/products/technotes/sequencing-sheet-format-specifications-technical-note-970-2017-004.pdf).

I will make the fix and add a test case! Thanks @andybearman!

**Comment by andybearman** [comment]
Thanks very much, really useful library by the way!

**Comment by clintval** [comment]
Fixed in #47. See my note too as `SampleSheet.write()` will always pad with commas. 

You can install off `master` or wait for a `v0.7.0` release.

If you would like that to not happen could you submit a new issue with the request and we could make it like:

```python
SampleSheet.write(handle, blank_lines=1, comma_pad=False)
```

Thanks for using the library! It's still pretty young so any feedback on if the API and methods are useful would be much appreciated.

Thanks!

**Comment by clintval** [comment]
@andybearman just made release `v0.7.0` which contains this feature!

Thanks again

https://github.com/clintval/sample-sheet/releases/tag/v0.7.0

**Comment by andybearman** [comment]
Brilliant, thanks @clintval!
