### ISSUE TITLE
Index vs index

### ISSUE THREAD

**Issue by slagelwa** [clintval/sample-sheet#51]
Recently downloaded some example data from Illumina and I noticed the sample sheet had "Index" in it, not "index".  Unfortunately wasn't able to read the sample sheet because of this.   FYI, the data header line looked like:

Sample_ID,Sample_Name,BASESPACE_SAMPLE_RESOURCE_ID,GenomeFolder,I7_Index_ID,I5_Index_ID,Index,Index2,Sample_Well,Manifest,FastqFolder

**Comment by clintval** [comment]
Thanks @slagelwa, indeed the manual does state that these entries should be case-insensitive.

https://www.illumina.com/content/dam/illumina-marketing/documents/products/technotes/sequencing-sheet-format-specifications-technical-note-970-2017-004.pdf

I'll mark this as a bug and try to get a patch in ASAP.

**Comment by clintval** [comment]
Hi @slagelwa I fixed this issue on `master` if you would like to try it. Please be aware I have made quite a few changes to the project and API and may have broken the API slightly in a few places.

Going forward (as I trend towards an official `v1`) I will update the documentation liberally here and provide deprecation warnings and change-logs:

http://sample-sheet.readthedocs.io/

Eager to hear your thoughts. I'll release on PyPi after a bit more fiddling on my end.
