### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by nuin** [clintval/sample-sheet#8]
When running

```python
import os
import sys
import csv
from sample_sheet import SampleSheet

url = 'https://raw.githubusercontent.com/clintval/sample-sheet/master/tests/resources/{}'
sample_sheet = SampleSheet(url.format('paired-end-single-index.csv'))

print sample_sheet
```

I get this

```bash
>> python3 SampleSheet.csv
  File "SampleSheet.csv", line 1
    [Header],,,,,,,,,,
             ^
SyntaxError: invalid syntax
```

both in the example SampleSheet and my own.

Running code installed with pip3, not the one on the repository.

**Comment by clintval** [comment]
Thanks! I'll check this out now.

**Comment by clintval** [comment]
Are you sure you are using Python 3.6? Your `print sample_sheet` statement suggests otherwise.

**Comment by nuin** [comment]
Yes, it worked ok from the console, it might be something on somewhere in my Python setup. I am using 3.6 anyway.

Thanks, I will close it.

**Comment by clintval** [comment]
No problem. Feel free to write back if you have any difficulty.

**Comment by nuin** [comment]
It worked fine, some dumb mistake on my end. I tested with your example and it worked fine. I will open another ticket, with a request more than an error.

Thanks again
