### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by mivade** [clintval/sample-sheet#82]
I'm experiencing two separate issues when trying to install this package:

## Install with conda

The README says to do the following:

```conda install -c bioconda sample-sheet```

However this results in a missing dependency:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - sample-sheet -> terminaltables

Current channels:
<truncated>
```

This can be fixed by explicitly including `-c conda-forge` like so:

```conda install -c bioconda -c conda-forge sample-sheet```

## Install with pip on bitbucket pipelines

Using Bitbucket pipelines to test a package, I get the following output when listing `sample-sheet` as a dependency in my `setup.py` and installing my package:

```
  Downloading https://files.pythonhosted.org/packages/e1/4e/c4af36fcf9f7d3364723a49ec802637e6dbe73725bd2be97e5c7647a0669/sample-sheet-0.9.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-py7rsp3d/sample-sheet/setup.py", line 20, in <module>
        long_description=Path('README.md').read_text(),
      File "/opt/miniconda3/envs/test/lib/python3.6/pathlib.py", line 1197, in read_text
        return f.read()
      File "/opt/miniconda3/envs/test/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1207: ordinal not in range(128)
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-py7rsp3d/sample-sheet/
```

Note that I do *not* get this error in a local development environment, so it could be specific to Bitbucket pipelines.

**Comment by clintval** [comment]
Thanks for reaching out!

Because I'm hosting on bioconda I think I'm explicitly relying on their setup instructions here:

https://bioconda.github.io/user/install.html#set-up-channels

I can definitely make the `README.md` much more clear by referencing the Bioconda docs but also providing an install command that has the channels in the correct order!

Thanks for pointing out.

---

Your second bug is very odd. What command was used to install?

Was it just a `pip install sample_sheet`?

**Comment by mivade** [comment]
No, I was running `pip install .` with my own package which included `sample-sheet` as a dependency. `pip install sample-sheet` locally worked just fine, however.

**Comment by clintval** [comment]
Ah I see the bug. I can patch. Thanks for reporting!

**Comment by clintval** [comment]
I'll try to get to later today.

**Comment by mivade** [comment]
Thanks!

**Comment by clintval** [comment]
Hi @mivade, thanks for reaching out!

🤞 I think I fixed both of your bugs.

1. The main README and hosted documentation have more accurate instructions for installing from Bioconda.
2. I changed `setup.py` to use file reading methods that do not rely on `pathlib.Path`.

The new release `0.9.1` is up on PyPi and can be installed with:

```bash
❯ pip install sample-sheet
```

I am still waiting on Bioconda to revision up the conda-hosted package:

https://github.com/bioconda/bioconda-recipes/pull/16196

Although there are no changes in the library from `0.9.0` to `0.9.1` the following should work regardless:

```bash
# After setting up Bioconda channels correctly: https://bioconda.github.io/user/install.html#set-up-channels
❯ conda install sample-sheet
```

Instead:

```bash
❯ conda install -c bioconda -c conda-forge -c defaults sample-sheet
```

**Comment by clintval** [comment]
I'm very interested in user-feedback because I would like to release a formal `v1.0` at some point this year which may include API breaking changes.

Feel free to ping me with ideas for enhancements, gripes, or other common uses you would like to see in this library.

**Comment by mivade** [comment]
@clintval thank you for your quick updates! I've confirmed that the updated version fixes the `pip install` issue.
